#! /bin/bash
branchName=$(git rev-parse --abbrev-ref HEAD) # 現在のブランチ名を取得
ticketBango=$(echo $branchName | perl -nle '/\/(\d+)_/ && print $1') # チケット番号を取得
firstLine=$(head -n1 $1)  # git commit --amendとの区別のために最初の一行を取得

if [ -z "$firstLine" ] ;then 
    perl -i.bak -pe "if ($. == 1) { s/^/\"#${ticketBango}\" / }" $1 # 「#チケット番号」をコミットメッセージのprefixとして挿入
fi
