#! /bin/bash

readonly COMMIT_MSG_FILE=$1
readonly COMMIT_SOURCE=$2

case "${COMMIT_SOURCE}" in
    commit) # -c/-C/--amendが含まれている場合
        : # 何もしない
    ;;
    *)
    branchName=$(git rev-parse --abbrev-ref HEAD) # 現在のブランチ名を取得
    ticketBango=$(echo $branchName | perl -nle '/\/(\d+)_/ && print $1') # チケット番号を取得
    perl -p -i.bak -e 'if ($. == 1) { s/^/#${ticketBango} / }' $COMMIT_MSG_FILE # 「#チケット番号」をコミットメッセージのprefixとして挿入
    ;;
esac
